version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:476653858691:task-definition/aws-cicd:1"
        LoadBalancerInfo:
          ContainerName: "aws-cicd"
          ContainerPort: 80
        PlatformVersion: "LATEST"